### PR TITLE
chore: support nest.js v8

### PR DESCRIPTION
**Pull request by 9renpoto**

### CODE REVIEW

**Comment by 9renpoto** [comment]
@fvilers  hi, could you please review ? :)

**Comment by fvilers** [comment]
Hi ! Thanks for your submission. I'll review it asap. I'm not using Algolia and NestJS for a long time, that's why this package hasn't evolved recently.

**Comment by 9renpoto** [comment]
thank you reviews :)
I'll pr for upgrade of algoliasearch next.

https://github.com/caddijp/nestjs-algolia/pull/4

**Comment by fvilers** [comment]
Hi ! I've migrated the library through all versions of NestJS to ensure backwards compatibility. Thanks again for you submission, I'll close this PR as I've migrated the code myself. I copied your unit test for the sake of having a test in the project :-)

Version 4.0.0 for NestJS 8 is published. 🔥

**Pull request closed without merging**
